version: "3.8"
   
services:
  web:
    build: .
    command: npm run start
    volumes:
      - /usr/src/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    networks:
      - default
  db:
    image: postgres:12
    env_file:
      - .env.postgres
    ports:
      - "5432:5432"
    networks:
      - default
