name: docker ci

on:
  push:
    branches: master

jobs:
  login:
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and publish 🐳
        run: |
          cd ${GITHUB_WORKSPACE}
          docker build . -t=nest-back-art-seven-api:build-$GITHUB_RUN_NUMBER
          docker tag nest-back-art-seven-api:build-$GITHUB_RUN_NUMBER caprilespe/nest-back-art-seven-api:build-$GITHUB_RUN_NUMBER
          docker push caprilespe/nest-back-art-seven-api:build-$GITHUB_RUN_NUMBER